keys:
  - &laptop age1t7nwy3fy8n7dk7ual8cpzw442n7ue7kldfj2ete55llf90fswves3u92ew
  - &serv age1xdwsd3s4703myzg2aq6gweq808zw0gdqk5lcylwhggmeus0lrcnskgs5td
  - &erying age1lp7hsz5wm6elvh0sgyvvlg30gqsl7lwds488fgkf73ugj77tddxqanmjd6
creation_rules:
  - path_regex: secrets/
    key_groups:
    - age:
      - *laptop
      - *serv
      - *erying

# remember to update keys if you change them :)
#
# ssh-keygen -t ed25519 # creates a keypair, default location is ~.ssh/ don't make a passphrase
#
# ssh-to-age --run "ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt" # convert ssh to age key
#
# age-keygen -y ~/.config/sops/age/keys.txt # outputs public age key, used above
#
# will save you around 10 minutes of your life figuring out what you've done wrong this time
#
# nix-shell -p sops
#
# sops updatekeys path/secret.ext
