cameras:
  testy:
    ffmpeg:
      inputs:
        - path: ffmpeg:http://192.168.87.22:/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=password
          input_args: preset-http-reolink
          roles:
            - detect
  driveway:
    best_image_timeout: 15
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_sub
        input_args: preset-rtsp-restream-low-latency
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/driveway
        roles:
        - record
    record:
      enabled: true
    zones:
      carpark:
        coordinates:  0,480,352,480,326,70,200,71,191,21,0,240
      verandah:
        coordinates: 1024,768,1024,442,584,465,621,768
  entry:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/entry
        roles:
        - detect
        - record
    motion:
      mask:
      - 0,768,305,768,170,0,0,0
      - 1024,0,1024,30,650,30,650,0
    record:
      enabled: true

database:
  path: /db/frigate.db

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detect:
  enabled: true
  fps: 4
  height: 480
  width: 640

go2rtc:
  streams:
    driveway: rtsp://user:password@192.168.87.20:554/h264Preview_01_main
    entry: rtsp://user:password@192.168.87.22:554/h264Preview_01_main
    driveway_sub: rtsp://user:password@192.168.87.20:554/h264Preview_01_sub
    entry_sub: rtsp://user:password@192.168.87.22:554/h264Preview_01_sub

logger:
  default: info
  logs:
    peewee: info
    ws4py: info

motion:
  threshold: 90

mqtt:
  client_id: frigate
  enabled: true
  host: 192.168.87.10
  password: frigate
  port: 1883
  stats_interval: 60
  topic_prefix: frigate
  user: frigate

objects:
  track:
  - cat
  - person
  - dog
  - bike

record:
  enabled: true
  events:
    objects:
    - cat
    - person
    - dog
    - bike
    post_capture: 10
    pre_capture: 6
    retain:
      default: 5
      mode: motion
  expire_interval: 60
  retain:
    days: 0
    mode: all
  sync_recordings: true

rtmp:
  enabled: false

snapshots:
  bounding_box: true
  clean_copy: true
  crop: false
  enabled: true
  quality: 70
  timestamp: false

ui:
  time_format: browser

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt