# gate proxy config

# https://connect.minekube.com/

connect:
  enabled: false
  name: yernar

config:
  bind: 0.0.0.0:25565
  onlineMode: true

  servers:
    server1: ${server1}:25565

  try:
    - server1

  status:
    # server image 64x64 base64 nintendo64
    favicon:
    showMaxPlayers: 1000
    logPingRequests: true
    announceForge: false
    motd: |
      §b LETS VISIT
      §b➞ §f${domain}      

  acceptTransfers: false
  bungeePluginChannelEnabled: true
  builtinCommands: true
  requireBuiltinCommandPermissions: false
  announceProxyCommands: true
  forceKeyAuthentication: true

  shutdownReason: |
    §c${domain} is going down...
    ...

  compression:
    threshold: 256
    level: -1

  connectionTimeout: 5s
  readTimeout: 30s
  failoverOnUnexpectedServerDisconnect: true
  onlineModeKickExistingPlayers: false
  debug: false

  forwarding:
    mode: legacy
    # velocitySecret: secret_here

  proxyProtocol: false

  quota:
    connections:
      enabled: true
      ops: 5
      burst: 10
      maxEntries: 1000
    logins:
      enabled: true
      burst: 3
      ops: 0.4
      maxEntries: 1000

  query:
    enabled: false
    port: 25577
    showPlugins: false

  auth:
    sessionServerUrl: https://sessionserver.mojang.com/session/minecraft/hasJoined

  lite:
    enabled: false