# i know passwords are currently exposed here, these are "temp"
cameras:
#
  driveway:
    best_image_timeout: 60
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/driveway_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/driveway
        input_args: preset-rtsp-restream
        roles:
        - record
    record:
      enabled: true
    # zones:
      #carpark:
      #  coordinates: 1315,235,793,267,768,73,471,407,0,954,0,1345,1357,1317
      #street:
      #  coordinates: 0,0,2560,0,2560,123,2560,147,1325,161,1320,223,806,259,766,40,0,897,0,326
      #front_lawn:
      #  coordinates: 2262,161,2560,155,2560,1074,1792,1120,1764,894,1384,924,1312,160
      #verandah:
      #  coordinates: 2560,1084,2560,1920,1543,1920,1440,1157
      #carpark_gate:
      #  coordinates: 1483,1920,0,1920,0,1385,1397,1358
#
  entry:
    best_image_timeout: 60
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/entry_sub
        input_args: preset-rtsp-restream
        roles:
        - detect
      - path: rtsp://127.0.0.1:8554/entry
        input_args: preset-rtsp-restream
        roles:
        - record
    # motion:
      # mask:
       #  - 0,1920,734,1920,638,1518,574,1215,529,795,508,777,481,154,495,101,492,0,0,0
    record:
      enabled: true
    # zones:
      # door_verandah:
        # coordinates: 1095,332,1610,614,1553,1100,1438,1141,1341,1205,1262,1280,1098,1328,878,1409,645,1503,581,1122,1084,1037
      # stairs_bed_window:
        # coordinates: 530,827,699,768,846,709,884,172,1069,180,1045,745,1023,1012,560,1109
      # side_fence:
        # coordinates: 843,260,504,388,533,795,858,709
#
database:
  path: /db/frigate.db
#
detect:
  enabled: true
  fps: 4
  height: 480
  width: 640
#
go2rtc:
  streams:
    driveway:
      - rtsp://frigate:Mj3iNSUJydpaaiT87d65NZgS9kh@192.168.87.20:554/h264Preview_01_main
    entry:
      - rtsp://frigate:Mj3iNSUJydpaaiT87d65NZgS9kh@192.168.87.22:554/h264Preview_01_main
    #
    driveway_sub:
      - rtsp://frigate:Mj3iNSUJydpaaiT87d65NZgS9kh@192.168.87.20:554/h264Preview_01_sub
    entry_sub:
      - rtsp://frigate:Mj3iNSUJydpaaiT87d65NZgS9kh@192.168.87.22:554/h264Preview_01_sub
#
logger:
  default: info
  logs:
    peewee: info
    ws4py: info
#
motion:
  threshold: 90
#
mqtt:
  client_id: frigate
  enabled: true
  host: 192.168.87.9
  password: $iFQhh^QXu2^r&s%!MX%h969PNW
  port: 1883
  stats_interval: 60
  topic_prefix: frigate
  user: frigate
#
objects:
  track:
  - cat
  - person
  - dog
  - bike
  - phone
  - package
#
record:
  enabled: true
  events:
    objects:
    - cat
    - person
    - dog
    - bike
    - phone
    - package
    post_capture: 10
    pre_capture: 6
    retain:
      default: 5
      mode: motion
  expire_interval: 60
  retain:
    days: 0
    mode: all
  sync_recordings: true
#
rtmp:
  enabled: false
#
snapshots:
  bounding_box: true
  clean_copy: true
  crop: false
  enabled: true
  quality: 90
  timestamp: true
#
ui:
  time_format: browser
#
ffmpeg:
  hwaccel_args: preset-vaapi
#
#detectors:
#   deepstack:
#     api_url: http://192.168.87.30:32168/v1/vision/detection
#     type: deepstack
#     api_timeout: 1 # seconds
#
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
#
birdseye:
  enabled: true
  width: 640
  height: 480