---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "homer.home"
subtitle: ""
logo: "logo.png"

header: true
footer: '<p> (づ ￣ ³￣)づ </p>'

connectivityCheck: true
defaults:
  layout: list
  colorTheme: dark

theme: neon
colors:
  light:
    highlight-primary: "#E3E6EE" # header background, group title icons
    highlight-secondary: "#B072D1" # navbar background, default tag color
    highlight-hover: "#1C1E26" # navbar links hover, search input background
    background: "#E3E6EE" # page background color
    card-background: "#DCDFE4" # service card background color
    text: "#1C1E26" # main text color
    text-header: "#1C1E26" # header text color
    text-title: "#1C1E26" # service card title color
    text-subtitle: "#1C1E26" # service card subtitle color
    card-shadow: rgb(228, 163, 130, 0.7) # #24A8B4 service card box-shadow
    link: "#DF5273" # links color (footer & message), service card icon color
    link-hover: "#E93C58" # links hover color (footer & message), service card icon hover color
  dark:
    highlight-primary: "#24A8B4" # header background, group title icons
    highlight-secondary: "#B072D1" # navbar background, default tag color
    highlight-hover: "#1C1E26" # navbar links hover, search input background
    background: "#1C1E26" # page background color
    card-background: "#232530" # service card background color
    text: "#DCDFE4" # main text color
    text-header: "#DCDFE4" # header text color
    text-title: "#DCDFE4" # service card title color
    text-subtitle: "#DCDFE4" # service card subtitle color
    card-shadow: rgb(228, 163, 130, 0.7) # #24A8B4 service card box-shadow
    link: "#DF5273" # links color (footer & message), service card icon color
    link-hover: "#24A8B4" # links hover color (footer & message), service card icon hover color

services:
  - name: "services"
    items:
      - name: "nginx-lan"
        icon: "fas fa-route fa-fw"
        subtitle: "Internal Reverse Proxy"
        tag: "proxy"
        url: "https://nginx.home/"

      - name: "nginx-wan"
        icon: "fas fa-globe-asia fa-fw"
        subtitle: "External Reverse Proxy"
        tag: "wan"
        url: "https://wan.home/"

      - name: "transmission"
        icon: "fas fa-download fa-fw"
        subtitle: "Linux ISO Downloader"
        tag: "torrent"
        url: "https://torrent.home/"

      - name: "adguard-erying"
        icon: "fas fa-ban fa-fw"
        subtitle: "DNS + DHCP + Ad Blocker"
        tag: "torrent"
        url: "https://adguard.erying.home/"

      - name: "adguard-serv"
        icon: "fas fa-ban fa-fw"
        subtitle: "DNS + DHCP + Ad Blocker"
        tag: "torrent"
        url: "https://adguard.serv.home/"

      - name: "jellyfin"
        icon: "fas fa-film fa-fw"
        subtitle: "Media Server"
        tag: "torrent"
        url: "https://jellyfin.home/"

      - name: "plex"
        icon: "fas fa-play-circle fa-fw"
        subtitle: "Media Server"
        tag: "torrent"
        url: "https://plex.home/"

      - name: "frigate"
        icon: "fas fa-video fa-fw"
        subtitle: "NVR"
        tag: "nvr"
        url: "https://frigate.home/"

      - name: "home-assistant"
        icon: "fas fa-house-user fa-fw"
        subtitle: "Smart Home Controls"
        tag: "haos"
        url: "https://haos.home/"

      - name: "orca-slicer"
        icon: "fas fa-cube fa-fw"
        subtitle: "3D Printer Slicer"
        tag: "slice"
        url: "https://orca.home/"

      - name: "mainsail"
        icon: "fas fa-cubes fa-fw"
        subtitle: "3D Printer Web-interface"
        tag: "print"
        url: "http://fwedee.home"

  - name: "devices"
    items:
      - name: "ap0"
        icon: "fas fa-wifi"
        subtitle: "OpenWRT Google WiFi"
        tag: "wifi"
        url: "https://ap0.home/"

      - name: "ap1"
        icon: "fas fa-wifi"
        subtitle: "OpenWRT Google WiFi"
        tag: "wifi"
        url: "https://ap1.home/"

      - name: "ap2"
        icon: "fas fa-wifi"
        subtitle: "OpenWRT Google WiFi"
        tag: "wifi"
        url: "https://ap2.home/"

      - name: "gateway"
        icon: "fas fa-ethernet"
        subtitle: "OpenWRT Ubiquiti EdgeRouter 4"
        tag: "gateway"
        url: "https://edge.home/"

      - name: "ups"
        icon: "fas fa-battery-empty fa-fw"
        subtitle: "Dell 1920 Rackmount UPS"
        tag: "ups"
        url: "https://ups.home/"