---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "homer.home"
subtitle: "local services"
logo: "logo.png"

header: true
footer: '<p> (づ ￣ ³￣)づ </p>'

connectivityCheck: true
defaults:
  layout: list
  colorTheme: dark

theme: neon
colors:
  light:
    highlight-primary: "#E3E6EE" #
    highlight-secondary: "#B072D1" # banner divider, card tags
    highlight-hover: "#1C1E26" #
    background: "#E3E6EE" #
    card-background: "#DCDFE4" #
    text: "#1C1E26" #
    text-header: "#1C1E26" #
    text-title: "#1C1E26" #
    text-subtitle: "#1C1E26" #
    card-shadow: rgb(228, 163, 130, 0.7) # #24A8B4 also used on footer
    link: "#DF5273" # used for icons
    link-hover: "#E93C58" # hover icons
  dark:
    highlight-primary: "#232530" #
    highlight-secondary: "#B072D1" # banner divider, card tags
    highlight-hover: "#1C1E26" #
    background: "#1C1E26" #
    card-background: "#232530" #
    text: "#DCDFE4" #
    text-header: "#DCDFE4" #
    text-title: "#DCDFE4" #
    text-subtitle: "#DCDFE4" #
    card-shadow: rgb(228, 163, 130, 0.3) # #24A8B4 also used on footer
    link: "#DF5273" # used for icons
    link-hover: "#E93C58" # hover icons

message:
  url: https://www.yomama-jokes.com/api/v1/jokes/random
  mapping:
    title: 'category'
    content: 'joke'
  refreshInterval: 10000
  style: "is-warning"
  icon: "fa fa-exclamation-triangle"


services:
  - name: "services"
    items:
      - name: "nginx-local"
        icon: "fas fa-route fa-fw"
        subtitle: "Internal Reverse Proxy"
        tag: "proxy"
        url: "https://nginx.home/"

      - name: "nginx-wan"
        icon: "fas fa-globe-asia fa-fw"
        subtitle: "External Reverse Proxy"
        tag: "proxy"
        url: "https://wan.home/"

      - name: "frigate"
        icon: "fas fa-video fa-fw"
        subtitle: "NVR"
        tag: "nvr"
        url: "https://frigate.home/"

      - name: "home-assistant"
        icon: "fas fa-house-user fa-fw"
        subtitle: "Smart Home Controls"
        tag: "haos"
        url: "https://haos.home/"

      - name: "plex"
        icon: "fas fa-house-user fa-fw"
        subtitle: "Media Server"
        tag: "plelx"
        url: "https://plex.home/"

  - name: "devices"
    items:
      - name: "ap0"
        icon: "fas fa-wifi"
        subtitle: "OpenWRT Google WiFi"
        tag: "wifi"
        url: "https://ap0.home/"

      - name: "ap1"
        icon: "fas fa-wifi"
        subtitle: "OpenWRT Google WiFi"
        tag: "wifi"
        url: "https://ap1.home/"

      - name: "ap2"
        icon: "fas fa-wifi"
        subtitle: "OpenWRT Google WiFi"
        tag: "wifi"
        url: "https://ap2.home/"

      - name: "gateway"
        icon: "fas fa-ethernet"
        subtitle: "OpenWRT Ubiquiti EdgeRouter 4"
        tag: "gateway"
        url: "https://edge.home/"

      - name: "ups"
        icon: "fas fa-battery-empty fa-fw"
        subtitle: "Dell 1920 Rackmount UPS"
        tag: "ups"
        url: "https://ups.home/"