---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "homer.home"
# subtitle: " "
logo: "logo.png"

header: true
footer: '<p> (づ ￣ ³￣)づ </p>'

connectivityCheck: false
defaults:
  layout: list
  colorTheme: dark

theme: neon
colors:
  light:
    highlight-primary: "#E3E6EE" #
    highlight-secondary: "#B072D1" # banner divider, card tags
    highlight-hover: "#1C1E26" #
    background: "#E3E6EE" #
    card-background: "#DCDFE4" #
    text: "#1C1E26" #
    text-header: "#1C1E26" #
    text-title: "#1C1E26" #
    text-subtitle: "#1C1E26" #
    card-shadow: rgb(228, 163, 130, 0.7) # #24A8B4 also used on footer
    link: "#DF5273" # used for icons
    link-hover: "#E93C58" # hover icons
  dark:
    highlight-primary: "#232530" #
    highlight-secondary: "#B072D1" # banner divider, card tags
    highlight-hover: "#1C1E26" #
    background: "#1C1E26" #
    card-background: "#232530" #
    text: "#DCDFE4" #
    text-header: "#DCDFE4" #
    text-title: "#DCDFE4" #
    text-subtitle: "#DCDFE4" #
    card-shadow: rgb(228, 163, 130, 0.7) # #24A8B4 also used on footer
    link: "#DF5273" # used for icons
    link-hover: "#E93C58" # hover icons

message:
  url: https://www.yomama-jokes.com/api/v1/jokes/random
  refreshInterval: 10000
  style: "is-warning"
  icon: "fa fa-exclamation-triangle"
  mapping:
    title: 'category'
    content: 'joke'

services:
  - name: "servers"
    icon: "fad fa-server"
    items:
      - name: ""
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        # target: "_blank" # optional html a tag target attribute
      - name: "UPS"
        logo: "assets/tools/sample2.png"
        subtitle: "Dell 1920"
        tag: "app"
        url: "https://ups.home/"