{
  secrets,
  pkgs,
  lib,
  ...
}: {
  systemd = {
    # root target
    targets."podman-compose-swag-root" = {
      unitConfig = {Description = "Root target generated by compose2nix.";};
      wantedBy = ["multi-user.target"];
    };

    services = {
      # container
      "podman-swag" = {
        serviceConfig = {
          Restart = lib.mkOverride 90 "always";
        };
        after = [
          "podman-network-swag.service"
          "podman-volume-swag.service"
        ];
        requires = [
          "podman-network-swag.service"
          "podman-volume-swag.service"
        ];
        partOf = ["podman-compose-swag-root.target"];
        wantedBy = ["podman-compose-swag-root.target"];
      };

      # network
      "podman-network-swag" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStop = "podman network rm -f swag";
        };
        script = ''podman network inspect swag || podman network create swag'';
        partOf = ["podman-compose-swag-root.target"];
        wantedBy = ["podman-compose-swag-root.target"];
      };
      # volume
      "podman-volume-swag" = {
        path = [pkgs.podman];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''podman volume inspect swag || podman volume create swag'';
        partOf = ["podman-compose-swag-root.target"];
        wantedBy = ["podman-compose-swag-root.target"];
      };
    };
  };

  virtualisation.oci-containers.containers."swag" = {
    image = "lscr.io/linuxserver/swag:latest";
    environment = {
      "CERTPROVIDER" = "";
      "DISABLE_F2B" = "";
      "DNSPLUGIN" = "cloudflare";
      "EMAIL" = "";
      "EXTRA_DOMAINS" = "";
      "ONLY_SUBDOMAINS" = "false";
      "PGID" = "1000";
      "PUID" = "1000";
      "PROPAGATION" = "";
      "STAGING" = "false";
      "SUBDOMAINS" = "www,";
      "SWAG_AUTORELOAD" = "";
      "SWAG_AUTORELOAD_WATCHLIST" = "";
      "TZ" = "Australia/Melbourne";
      "URL" = "${secrets.domain.two}";
      "VALIDATION" = "http";
      DOCKER_MODS = "linuxserver/mods:swag-dashboard";
      # multiple mods seperated by |
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "swag:/config:rw"
    ];
    ports = [
      "443:443/tcp"
      "80:80/tcp"
      "81:81/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--network-alias=swag"
      "--network=swag"
      "--network=macvlan_lan:ip=${secrets.ip.swag},interface_name=eth0"
    ];
  };
}
