---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "yur.mom"
subtitle: "now on the internet"

header: true
footer: '<p> (づ ￣ ³￣)づ </p>'

connectivityCheck: false
defaults:
  layout: list
  colorTheme: dark

links:
  - name: "homer - this page"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
  - name: "my nixos configs"
    icon: "fas fa-book"
    url: "https://codeberg.org/kye/nixos"
  # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
  # see url field and assets/page.yml used in this example:
  # - name: "Second Page"
  #   icon: "fas fa-file-alt"
  #   url: "#page2"

theme: neon
colors:
  light:
    highlight-primary: "#E3E6EE" # header background, group title icons
    highlight-secondary: "#B072D1" # navbar background, default tag color
    highlight-hover: "#1C1E26" # navbar links hover, search input background
    background: "#E3E6EE" # page background color
    card-background: "#DCDFE4" # service card background color
    text: "#1C1E26" # main text color
    text-header: "#1C1E26" # header text color
    text-title: "#1C1E26" # service card title color
    text-subtitle: "#1C1E26" # service card subtitle color
    card-shadow: rgb(228, 163, 130, 0.7) # #24A8B4 service card box-shadow
    link: "#DF5273" # links color (footer & message), service card icon color
    link-hover: "#E93C58" # links hover color (footer & message), service card icon hover color
  dark:
    highlight-primary: "#24A8B4" # header background, group title icons
    highlight-secondary: "#B072D1" # navbar background, default tag color
    highlight-hover: "#1C1E26" # navbar links hover, search input background
    background: "#1C1E26" # page background color
    card-background: "#232530" # service card background color
    text: "#DCDFE4" # main text color
    text-header: "#DCDFE4" # header text color
    text-title: "#DCDFE4" # service card title color
    text-subtitle: "#DCDFE4" # service card subtitle color
    card-shadow: rgb(228, 163, 130, 0.7) # #24A8B4 service card box-shadow
    link: "#DF5273" # links color (footer & message), service card icon color
    link-hover: "#24A8B4" # links hover color (footer & message), service card icon hover color

services:
  - name: "her things"
    icon: "fas fa-hand-holding-heart fa-fw"

    items:
      - name: "plex"
        icon: "fas fa-tv"
        subtitle: "mom's special movies"
        tag: "plex"
        url: "https://www.yur.mom/plex"

      - name: "request"
        icon: "fas fa-hand-middle-finger"
        subtitle: "now taking requests"
        tag: "overseerr"
        url: "https://www.yur.mom/request"

      - name: "minecraft"
        icon: "fas fa-cubes"
        subtitle: "break some bricks"
        tag: "minecraft"
        type: "CopyToClipboard"
        clipboard: "www.yur.mom"
